apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cgv-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cgv-api.labels" . | nindent 4 }}
  # 이 어노테이션이 쿠버네티스 서비스 어카운트와 AWS IAM 역할을 연결
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::732739477448:role/dev-EKS-App-Role"
